# Generated by Django 5.2.15 on 2026-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_paid_at_order_provider_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('completed', 'Завершен'), ('canceled', 'Отменен'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20),
        ),
    ]
